name: Build and Test V2

on: workflow_dispatch

env:
  AWS_REGION: eu-west-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      id-token: write
      contents: write
    steps:
      - #id: build-and-test
#        name: Build and Test
        uses: mgorski-mg/northmill-gh-poc-actions/action-build-test@v1