name: Build and Test V3

on: [ push, workflow_dispatch ]

env:
  AWS_REGION: eu-west-1

jobs:
  build-and-test:
    permissions:
      checks: write
      id-token: write
      contents: write
#    uses: octo-org/another-repo/.github/workflows/workflow.yml@v1
    uses: mgorski-mg/northmill-gh-poc-actions/.github/workflows/build-test.yaml@v2